### ISSUE TITLE
v1.0.1 has a merge error in the event scope patch

### ISSUE THREAD

**Issue by micahscopes** [skatejs/cloudydom#2]
v1.0.1 contained what looks like a merge error here: https://github.com/skatejs/cloudydom/blob/v1.0.1/src/patch-events.js#L282-L283

the base branch has fixed this: https://github.com/skatejs/cloudydom/blob/base/src/patch-events.js#L282

@matthewp how far off do you think a new version is?

**Comment by matthewp** [comment]
Thanks! Can have this fixed by the morning at the latest. Not at a computer at the moment.

A good reason to get our testing figured out. 😑

**Comment by matthewp** [comment]
It's fixed in master. Not having tests to run is a bit of a blocker. Need to fix that soon.

**Comment by matthewp** [comment]
Released 1.0.2

**Comment by treshugart** [comment]
@matthewp re tests, what's the blocker here? Is it Travis on our end? Or is it that tests were just never running in the first place on shadydom's side?

**Comment by matthewp** [comment]
Ok, switched Bram to use cloudydom as a sanity check: https://github.com/matthewp/bram/pull/43

@treshugart A few blockers 

1. Tests do not pass locally (for me at least).
2. I don't understand the test infrastructure (yet, haven't made a strong effort to try)
3. No CI yet, of course, but need 1 and 2 before doing that.

**Comment by matthewp** [comment]
Closing this as the issue here is resolved. Opened https://github.com/skatejs/cloudydom/issues/3 about tests.

**Comment by treshugart** [comment]
> Ok, switched Bram to use cloudydom as a sanity check: matthewp/bram#43

All of Skate's tests are running against cloudy, too.

**Comment by micahscopes** [comment]
I successfully ran tests for skatejs-web-component against cloudydom/base
